# Generated by Django 3.2.9 on 2022-01-19 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20220120_0025'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_password_changed',
            field=models.BooleanField(default=False),
        ),
    ]
