# Generated by Django 3.2.9 on 2022-02-11 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_account_is_password_changed'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='firebase_uid',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
