# Generated by Django 3.2.9 on 2022-02-25 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20220212_0120'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='country_code',
            field=models.CharField(default='+91', max_length=5, verbose_name='Country Code'),
        ),
    ]
