# Generated by Django 3.2.9 on 2022-02-26 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_account_country_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='country_code',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Country Code'),
        ),
    ]
