# Generated by Django 3.2.9 on 2021-12-09 09:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Battery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('battery_number', models.CharField(max_length=50, verbose_name='battery number')),
                ('capacity', models.CharField(max_length=100, verbose_name='battery capacity')),
                ('onboarding_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='onboarding date')),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imei_number', models.CharField(max_length=100, verbose_name='IMEI Number')),
                ('device_type', models.CharField(max_length=100, verbose_name='device type')),
                ('onboarding_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='onboarding date')),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='driver name')),
                ('phone_number', models.CharField(max_length=10, verbose_name='phone number')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_id', models.CharField(max_length=50, verbose_name='Vehicle Id')),
                ('make', models.CharField(max_length=50, verbose_name='make')),
                ('model', models.CharField(max_length=50, verbose_name='model')),
                ('year', models.CharField(max_length=4, verbose_name='year')),
                ('tag', models.CharField(blank=True, max_length=255, null=True, verbose_name='tag')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='created at')),
                ('battery_id', models.ForeignKey(max_length=255, on_delete=django.db.models.deletion.CASCADE, to='Vehicle.battery', verbose_name='battery id')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Vehicle.device', verbose_name='device')),
            ],
        ),
    ]
