# Generated by Django 3.2.9 on 2022-01-29 04:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Vehicle', '0002_auto_20220120_0025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='battery_id',
            field=models.ForeignKey(max_length=255, on_delete=django.db.models.deletion.CASCADE, related_name='vehicle', to='Vehicle.battery', verbose_name='battery id'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle', to='Vehicle.device', verbose_name='device'),
        ),
    ]
