# Generated by Django 3.2.9 on 2022-02-06 12:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Vehicle', '0007_auto_20220206_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battery',
            name='uuid',
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID'),
            ),
        migrations.AlterField(
            model_name='device',
            name='uuid',
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID'),
            ),
        migrations.AlterField(
            model_name='vehicle',
            name='uuid',
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID'),
            ),
    ]
