# Generated by Django 3.2.9 on 2022-02-15 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vehicle', '0008_auto_20220206_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='battery',
            name='max_distance',
            field=models.FloatField(default=140, verbose_name='Maximum distance on full battery (km)'),
        ),
        migrations.AddField(
            model_name='battery',
            name='max_voltage',
            field=models.FloatField(default=52.5, verbose_name='maximum battery volatage'),
        ),
        migrations.AddField(
            model_name='battery',
            name='min_voltage',
            field=models.FloatField(default=42, verbose_name='minimum battery volatage'),
        ),
    ]
