# Generated by Django 3.2.9 on 2022-02-18 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vehicle', '0009_auto_20220215_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battery',
            name='max_voltage',
            field=models.FloatField(default=56, verbose_name='maximum battery volatage'),
        ),
    ]
