# Generated by Django 3.2.9 on 2022-02-18 03:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Vehicle', '0011_trip'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID'),
        ),
    ]
