# Generated by Django 3.2.9 on 2022-02-24 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vehicle', '0015_alter_trip_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='vin_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='VIN number'),
        ),
    ]
