# Generated by Django 3.2.9 on 2022-02-27 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vehicle', '0017_livestatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='livestatus',
            name='created_at',
            field=models.DateField(auto_now=True, verbose_name='created at'),
        ),
    ]
