# Generated by Django 3.2.9 on 2022-02-27 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vehicle', '0018_livestatus_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_scl_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Vehicle SCL ID'),
        ),
    ]
