# Generated by Django 3.2.9 on 2022-03-01 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vehicle', '0019_vehicle_vehicle_scl_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='vehicle_scl_id',
        ),
        migrations.AddField(
            model_name='device',
            name='vehicle_scl_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Vehicle SCL ID'),
        ),
        migrations.AlterField(
            model_name='battery',
            name='max_voltage',
            field=models.FloatField(default=53, verbose_name='maximum battery volatage'),
        ),
        migrations.AlterField(
            model_name='battery',
            name='min_voltage',
            field=models.FloatField(default=37, verbose_name='minimum battery volatage'),
        ),
    ]
