# Generated by Django 3.2.9 on 2022-01-16 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('report_csv', models.FileField(blank=True, default=None, null=True, unique=True, upload_to='reports')),
            ],
        ),
    ]
