# Generated by Django 3.2.9 on 2022-01-26 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0004_alter_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ktp_image',
            field=models.ImageField(blank=True, null=True, upload_to='ktp'),
        ),
        migrations.AddField(
            model_name='profile',
            name='sim_image',
            field=models.ImageField(blank=True, null=True, upload_to='sim'),
        ),
    ]
