# Generated by Django 3.2.9 on 2022-01-26 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0005_auto_20220126_2109'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='document_verification_status',
            field=models.CharField(choices=[('accepted', 'Accepted'), ('rejected', 'Rejected'), ('pending', 'Pending')], default='pending', max_length=100, verbose_name='Verification Status'),
        ),
    ]
