# Generated by Django 3.2.9 on 2022-01-27 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0007_auto_20220126_2126'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='uid',
            new_name='ktp_number',
        ),
    ]
