# Generated by Django 3.2.9 on 2022-02-06 07:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0009_alter_profile_ktp_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='uuid',
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, null=True, verbose_name='UUID'),
        ),
        migrations.AddField(
            model_name='role',
            name='uuid',
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, null=True, verbose_name='UUID'),
        ),
    ]
