# Generated by Django 3.2.9 on 2022-02-06 12:06

from django.db import migrations
import uuid


def gen_uuid_profile(apps, schema_editor):
    MyModel = apps.get_model('Profile', 'Profile')
    for row in MyModel.objects.all():
        row.uuid = uuid.uuid4()
        row.save(update_fields=['uuid'])


def gen_uuid_role(apps, schema_editor):
    MyModel = apps.get_model('Profile', 'Role')
    for row in MyModel.objects.all():
        row.uuid = uuid.uuid4()
        row.save(update_fields=['uuid'])


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0010_auto_20220206_1437'),
    ]

    operations = [
        migrations.RunPython(
            gen_uuid_profile, reverse_code=migrations.RunPython.noop),
        migrations.RunPython(
            gen_uuid_role, reverse_code=migrations.RunPython.noop),

    ]
