# Generated by Django 3.2.9 on 2022-02-06 12:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0011_populate_uuid_values'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='uuid',
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID'),
        ),
        migrations.AlterField(
            model_name='role',
            name='uuid',
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID'),
        ),
    ]
