# Generated by Django 3.2.9 on 2022-02-07 17:37

from django.db import migrations, models
import ev.helpers
import ev.storages


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0013_profile_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, storage=ev.storages.ProfilePicStorageS3(), upload_to=ev.helpers.get_image_upload_path),
        ),
    ]
