# Generated by Django 3.2.9 on 2022-02-07 17:56

from django.db import migrations, models
import ev.helpers
import ev.storages
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0014_profile_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('ktp_image', models.ImageField(blank=True, default='ktp/bg2.png', null=True, storage=ev.storages.KtpStorageS3, upload_to=ev.helpers.get_image_upload_path)),
                ('sim_image', models.ImageField(blank=True, default='ktp/bg2.png', null=True, storage=ev.storages.SimStorageS3, upload_to=ev.helpers.get_image_upload_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
