# Generated by Django 3.2.9 on 2022-02-08 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0016_profile_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='sim_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='SIM Number'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='ktp_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='KTP Number'),
        ),
    ]
