# Generated by Django 3.2.9 on 2022-02-10 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0017_auto_20220208_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Profile.documents'),
        ),
    ]
