# Generated by Django 3.2.9 on 2022-02-10 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0018_profile_document'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Documents',
            new_name='Document',
        ),
    ]
