# Generated by Django 3.2.9 on 2022-02-11 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0019_rename_documents_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='document',
        ),
        migrations.DeleteModel(
            name='Document',
        ),
    ]
