# Generated by Django 3.2.9 on 2022-02-18 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0020_auto_20220211_0839'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='phone_number',
        ),
    ]
